In [ ]:
original_list = [5,6,7]
print("Öriginal List:", original_list)
original_list.append(4)
print("Modified List:", original_list)
original_tuple = (1,2,3)
print("Original Tuple:", original_tuple)

Öriginal List: [5, 6, 7]
Modified List: [5, 6, 7, 4]
Original Tuple: (1, 2, 3)


In [ ]:
age=20
pi=3.14
temperature =10.8
print("print type of variable age =", type(age))
print("data type of varibale pi=",type(pi))
print("data type of variable temperature=", type(temperature))

print type of variable age = <class 'int'>
data type of varibale pi= <class 'float'>
data type of variable temperature= <class 'float'>


In [ ]:
name = "Aashra"
greeting = "Namaste"
address ="Handigaun"
print("Data type of the variable name =", type(name))
print("Data type of the variable greeting = ",type(greeting))
print("Data type of the variable address = ", type(address))

print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])

print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:" ,name[:2])
print("Substring starting from the third letter is:", name[2:])

Data type of the variable name = <class 'str'>
Data type of the variable greeting =  <class 'str'>
Data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: a
The second letter to the fourth of the name is: ash
The first two letters of the name are: Aa
Substring starting from the third letter is: shra


In [ ]:
list1 = [3,5,7,9]
mixed_list = [25,"What", True]
mixed_list[0] = False
mixed_list

[False, 'What', True]

In [ ]:
colors = ("purple", "green", "red","pink")
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
colors

First element: purple
Last two elements: ('red', 'pink')
Middle two elements: ('green', 'red')


('purple', 'green', 'red', 'pink')

In [ ]:
person = {"name":"Aashra","age":20,"city":"Kathmandu"}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is Aashra. I am 20 years old and I live at Kathmandu.
All keys: ['name', 'age', 'city']
All values: ['Aashra', 20, 'Kathmandu']


In [ ]:
unique_numbers = {3,4,7,7,7,7,8,9}
print(unique_numbers)

{3, 4, 7, 8, 9}


In [ ]:
is_teacher =False
has_degree = True
print("Data type of the variable is_student =",type(is_teacher))
print("Data type of the variable has_license =",type(has_degree))

Data type of the variable is_student = <class 'bool'>
Data type of the variable has_license = <class 'bool'>


In [ ]:
num = -9
if num >0:
  print("Positive")
elif num == 0:
  print("Zero")
else:
  print("Negative")

Negative


In [ ]:
x = 4
y = 90
if x > 0 and y < 20:
    print("Both conditions are true")
if x > 0 or y > 20:
    print("At least one condition is true")
if not x == 0:
    print("x is not equal to 0")

At least one condition is true
x is not equal to 0


In [ ]:
x = True
y = False
if x and y:
    print("Both conditions are true")
else:
    print("At least one condition is false")
if x or y:
  print("At least one condition is true")
else:
  print("Both conditions are false")
if not x:
  print("x is false")
else:
  print("x is true")

At least one condition is false
At least one condition is true
x is true


In [ ]:
fruits = ["cherry","watermelon","honeydew"]
for fruit in fruits:
    print(fruit)

count = 0
while count < 5:
    print ("Count is: ",count)
    count += 1

fruits = ["cherry","watermelon","strawberry"]
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit == "cherry":
        break

    print("loop 2")
    for fruit in fruits:
        if fruit == "cherry":
            continue
        else:
            print(fruit)

cherry
watermelon
honeydew
Count is:  0
Count is:  1
Count is:  2
Count is:  3
Count is:  4
loop 1
cherry


In [ ]:
print("Goodbye Everybody")
length = len("Namaste")
data_type = type(42)
total = sum([1, 2, 3])

Goodbye Everybody


In [ ]:
# str.upper()
message = "hello".upper()
# list.append()
fruits = ["apple", "banana"]
fruits.append("cherry")
# dict.get()
info = {"name": "Aashra", "age": 20}
age = info.get("age")

In [ ]:
def temperature_converter():
    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")
    if choice == "1":
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}C is equal to {fahrenheit}F")
        return fahrenheit
    elif choice == "2":
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}F is equal to {celsius}C")
        return celsius
    else:
        print("Invalid choice. Please enter 1 or 2.")
    return None

temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 1
Enter temperature in Celsius: 27
27.0C is equal to 80.6F


80.6

In [ ]:
x = 67
def print_global():
  print(x)
print_global()

67


In [ ]:
def print_local():
    y = 5
    print(y)

print_local()
print(y)

5
False


In [ ]:
x = 10
def modify_global():
    global x
    x = 20

modify_global()
print(x)

20


In [ ]:
#Task01: Create a Python program that converts between different units of measurement.
def m_to_ft(meters):
    return meters * 3.280

def ft_to_m(feet):
    return feet / 3.280

def kg_to_lbs(kilogram):
    return kilogram * 2.204

def lbs_to_kg(pounds):
    return pounds / 2.204

def l_to_gal(liter):
    return liter * 0.2641

def gal_to_l(gallon):
    return gallon / 0.2641

def conversion():
    try:
        print("Choose a conversion type: ")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")
        choice = int(input("Enter your choice (1-3): "))

        if choice == 1:
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            choice2 = int(input("Enter your choice (1-2): "))
            value = float(input("Enter your value to convert: "))
            if choice2 == 1:
                result = m_to_ft(value)
                print(f"{value}m = {result}ft")
            elif choice2 == 2:
                result = ft_to_m(value)
                print(f"{value}ft = {value}m")
            else:
                print("Invalid choice. Please try again!")

        elif choice == 2:
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            choice2 = int(input("Enter your choice (1-2): "))
            value = float(input("Enter your value to convert: "))
            if (choice2 == 1):
                result = kg_to_lbs(value)
                print(f"{value}kg = {result}lbs")
            elif (choice2 == 2):
                result = lbs_to_kg(value)
                print(f"{value}lbs = {result}kg")
            else:
                print("Invalid choice. Please try again!")

        elif choice == 3:
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            choice2 = int(input("Enter your choice (1-2): "))
            value = float(input("Enter your value to convert: "))
            if (choice2 == 1):
                result = l_to_gal(value)
                print(f"{value}l = {result}gal")
            elif (choice2 == 2):
                result = gal_to_l(value)
                print(f"{value}gal = {result}l")
            else:
                print("Invalid choice. Please try again!")

        else:
            print("Invalid input. Please try again!")

    except ValueError:
        print("Invalid input. Please enter a number.")

conversion()

Choose a conversion type: 
1. Length
2. Weight
3. Volume
Enter your choice (1-3): 3
1. Liters to Gallons
2. Gallons to Liters
Enter your choice (1-2): 1
Enter your value to convert: 1
1.0l = 0.2641gal


In [ ]:
#Task02: Create a Python program that performs various mathematical operations on a list of numbers.
def calculate_sum(numbers):
    return sum(numbers)

def calculate_avg(numbers):
    return sum(numbers) / len(numbers) if numbers else 0

def find_max(numbers):
    return max(numbers)

def find_min(numbers):
    return min(numbers)

def main():
    try:
        print("Choose a mathematical operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = int(input("Enter your choice (1-4): "))
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            print("Error: The list of numbers cannot be empty.")
            return

        if choice == 1:
            print(f"Sum: {calculate_sum(numbers)}")
        elif choice == 2:
            print(f"Average: {calculate_avg(numbers)}")
        elif choice == 3:
            print(f"Maximum: {find_max(numbers)}")
        elif choice == 4:
            print(f"Minimum: {find_min(numbers)}")
        else:
            print("Invalid choice.")
    except ValueError:
        print("Invalid input. Please enter numeric values.")
main()


Choose a mathematical operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Enter numbers separated by spaces: 2 8
Sum: 10.0


In [ ]:
#Extract Every Other Element:
def extract_every_other(lst):
    return lst[::2]

def main():
    user_input = input("Enter elements separated by space: ").split()
    print(f"List:", user_input)
    print(f"Every other element in the list: {extract_every_other(user_input)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 5 8 3 0 1 7
List: ['5', '8', '3', '0', '1', '7']
Every other element in the list: ['5', '3', '1']


In [ ]:
#Slice a Sublist
def get_sublist(lst, start, end):
    return lst[start:end+1]

def main():
    user_input = input("Enter elements separated by space: ").split()
    start = int(input("Enter start element: "))
    end = int(input("Enter end element: "))
    print(f"List:", user_input)
    print(f"Sliced Sublist: {get_sublist(user_input, start, end)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 5 8 3 0 1 7
Enter start element: 2
Enter end element: 5
List: ['5', '8', '3', '0', '1', '7']
Sliced Sublist: ['3', '0', '1', '7']


In [ ]:
#Reverse a List Using Slicing:
def reverse_list(lst):
    return lst[::-1]

def main():
    user_input = input("Enter elements separated by space: ").split()
    print(f"List:", user_input)
    print(f"Reversed List: {reverse_list(user_input)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 9 4 7 2 5 3 1
List: ['9', '4', '7', '2', '5', '3', '1']
Reversed List: ['1', '3', '5', '2', '7', '4', '9']


In [ ]:
# Remove the First and Last Elements:
def remove_first_last(lst):
    return lst[1:-1]

def main():
    user_input = input("Enter elements separated by space: ").split()
    print(f"List:", user_input)
    print(f"Removed first and last elements from list: {remove_first_last(user_input)}")

if __name__ == "__main__":
    main()

Enter elements separated by space:  9 4 7 2 5 3 1
List: ['9', '4', '7', '2', '5', '3', '1']
Removed first and last elements from list: ['4', '7', '2', '5', '3']


In [ ]:
#Get the First n Elements:
def get_first_n(lst, n):
    return lst[:n]

def main():
    user_input = input("Enter elements separated by space: ").split()
    n = int(input("Enter the number of elements to be displayed: "))
    print(f"List:", user_input)
    print(f"First {n} elements: {get_first_n(user_input, n)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 9 4 7 2 5 3 1
Enter the number of elements to be displayed: 4
List: ['9', '4', '7', '2', '5', '3', '1']
First 4 elements: ['9', '4', '7', '2']


In [ ]:
#Extract Elements from the End:
def get_last_n(lst, n):
    return lst[-n:]

def main():
    user_input = input("Enter elements separated by space: ").split()
    n = int(input("Enter the number of elements to be displayed from last: "))
    print(f"List:", user_input)
    print(f"Every other element in the list: {get_last_n(user_input, n)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 9 4 7 2 5 3 1
Enter the number of elements to be displayed from last: 3
List: ['9', '4', '7', '2', '5', '3', '1']
Every other element in the list: ['5', '3', '1']


In [ ]:
#Extract Elements in Reverse Order:
def reverse_skip(lst):
    return lst[-2::-2]

def main():
    user_input = input("Enter elements separated by space: ").split()
    print(f"List:", user_input)
    print(f"Elements in reverse order starting from second-to-last: {reverse_skip(user_input)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 9 4 7 2 5 3 1
List: ['9', '4', '7', '2', '5', '3', '1']
Elements in reverse order starting from second-to-last: ['3', '2', '4']


In [ ]:
#Flatten a Nested List
def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(input(f"Enter element {j+1} of sublist {i+1}: "))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Flattened List:", flatten(list1))

if __name__ == "__main__":
    main()


Enter the number of sublists: 2
Enter the number of elements in sublist 1: 2
Enter element 1 of sublist 1: 5
Enter element 2 of sublist 1: 6
Enter the number of elements in sublist 2: 3
Enter element 1 of sublist 2: 9
Enter element 2 of sublist 2: 2
Enter element 3 of sublist 2: 7
Original Nested List: [['5', '6'], ['9', '2', '7']]
Flattened List: ['5', '6', '9', '2', '7']


In [ ]:
# Accessing Nested List Elements
def access_nested_element(lst, indices):
    elem = lst
    for index in indices:
        elem = elem[index]
    return elem

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(input(f"Enter element {j+1} of sublist {i+1}: "))
        list1.append(sublist)

    print("Original Nested List:", list1)

    indices = list(map(int, input("Enter indices separated by space: ").split()))

    try:
        print("Element at indices", indices, ":", access_nested_element(list1, indices))
    except IndexError:
        print("Error: Indices out of range!")

if __name__ == "__main__":
    main()


Enter the number of sublists: 2
Enter the number of elements in sublist 1: 1
Enter element 1 of sublist 1: 2
Enter the number of elements in sublist 2: 3
Enter element 1 of sublist 2: 4
Enter element 2 of sublist 2: 5
Enter element 3 of sublist 2: 6
Original Nested List: [['2'], ['4', '5', '6']]
Enter indices separated by space: 2
Error: Indices out of range!


In [ ]:
#Sum of All Elements in a Nested List
def sum_nested(lst):
    return sum(flatten(lst))

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Sum of all elements:", sum_nested(list1))

if __name__ == "__main__":
    main()


Enter the number of sublists: 2
Enter the number of elements in sublist 1: 1
Enter element 1 of sublist 1: 2
Enter the number of elements in sublist 2: 3
Enter element 1 of sublist 2: 4
Enter element 2 of sublist 2: 5
Enter element 3 of sublist 2: 6
Original Nested List: [[2], [4, 5, 6]]
Sum of all elements: 17


In [ ]:
#Remove Specific Element from a Nested List
def remove_element(lst, elem):
    if isinstance(lst, list):
        return [remove_element(sublist, elem) for sublist in lst if sublist != elem]
    return lst if lst != elem else None

def clean_list(lst):
    if isinstance(lst, list):
        return [clean_list(item) for item in lst if item is not None]
    return lst

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    elem = int(input("Enter element to remove: "))
    modified_list = clean_list(remove_element(list1, elem))

    print("Original Nested List:", list1)
    print("Modified list:", modified_list)

if __name__ == "__main__":
    main()


Enter the number of sublists: 2
Enter the number of elements in sublist 1: 3
Enter element 1 of sublist 1: 4
Enter element 2 of sublist 1: 5
Enter element 3 of sublist 1: 6
Enter the number of elements in sublist 2: 2
Enter element 1 of sublist 2: 4
Enter element 2 of sublist 2: 8
Enter element to remove: 1
Original Nested List: [[4, 5, 6], [4, 8]]
Modified list: [[4, 5, 6], [4, 8]]


In [ ]:
#Find the Maximum Element in a Nested List
def find_max(lst):
    return max(flatten(lst))

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Maximum element:", find_max(list1))

if __name__ == "__main__":
    main()

Enter the number of sublists: 2
Enter the number of elements in sublist 1: 1
Enter element 1 of sublist 1: 2
Enter the number of elements in sublist 2: 3
Enter element 1 of sublist 2: 4
Enter element 2 of sublist 2: 5
Enter element 3 of sublist 2: 6
Original Nested List: [[2], [4, 5, 6]]
Maximum element: 6


In [ ]:
#Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    return flatten(lst).count(elem)

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    elem = int(input("Enter element to find: "))

    print("Original Nested List:", list1)
    print("Occurrences of element:", count_occurrences(list1, elem))

if __name__ == "__main__":
    main()

Enter the number of sublists: 1
Enter the number of elements in sublist 1: 2
Enter element 1 of sublist 1: 3
Enter element 2 of sublist 1: 4
Enter element to find: 5
Original Nested List: [[3, 4]]
Occurrences of element: 0


In [ ]:
#Flatten a List of Lists of Lists
def deep_flatten(lst):
    return flatten(lst)

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(input(f"Enter element {j+1} of sublist {i+1}: "))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Deep Flattened List:", deep_flatten(list1))

if __name__ == "__main__":
    main()

In [ ]:
#Nested List Average
def average_nested(lst):
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Average of elements:", average_nested(list1))

if __name__ == "__main__":
    main()

Enter the number of sublists: 1
Enter the number of elements in sublist 1: 2
Enter element 1 of sublist 1: 3
Enter element 2 of sublist 1: 4
Original Nested List: [[3, 4]]
Average of elements: 3.5


In [ ]:
import numpy as np

arr_zeros = np.zeros((2,3))
print(" A zeros array is \n", arr_zeros, "with dimensions", arr_zeros.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [ ]:
zero_dim_array = np.array(5)
one_dim_array = np.array([5, 6, 7])
n_dim_array = np.array([[5, 6], [7, 8]])

for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[5 6 7]
Dimension: 1
Data type: int64

Array:
[[5 6]
 [7 8]]
Dimension: 2
Data type: int64



In [ ]:
#.ndim Number of Dimensions:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim)
# For a 2-D array:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr_2d.ndim)
#For a 3-D array:
arr_3d = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print("Dimension of 3d array: {arr_3d.ndim}")

#.shape Shape of the Array:
print("Shape of 1d array: {arr_1d.shape}")
print("Shape of 2d array: {arr_2d.shape}")
print("Shape of 3d array: {arr_3d.shape}")

#.size Total Number of Elements
print("Size of 1d array: {arr_1d.size}")
print("Size of 2d array: {arr_2d.size}")
print("Size of 3d array: {arr_3d.size}")

#.dtype Data Type of Elements
print("Datatype of 1d array: {arr_1d.dtype}")
arr_float = np.array([1.1, 2.2, 3.3])
print("Datatype of float array: {arr_float.dtype}")

# .itemsize Size of Each Element in Bytes
print("Size of items in 1d array: {arr_1d.itemsize}")

#.nbytes Total Memory Consumption
print("Total memory Consumption: {arr_1d.nbytes}")

#print(arr_1d.nbytes)
print("Transposed version of 2D array: {arr_2d.T}")

#.flat Flattening the Array
for item in arr_2d.flat:
    print(item, end=" ")

#.real and .imag - Real and Imaginary Parts
arr_complex = np.array([1+2j, 3+4j])


1
2
Dimension of 3d array: {arr_3d.ndim}
Shape of 1d array: {arr_1d.shape}
Shape of 2d array: {arr_2d.shape}
Shape of 3d array: {arr_3d.shape}
Size of 1d array: {arr_1d.size}
Size of 2d array: {arr_2d.size}
Size of 3d array: {arr_3d.size}
Datatype of 1d array: {arr_1d.dtype}
Datatype of float array: {arr_float.dtype}
Size of items in 1d array: {arr_1d.itemsize}
Total memory Consumption: {arr_1d.nbytes}
Transposed version of 2D array: {arr_2d.T}
1 2 3 4 5 6 

In [ ]:
import numpy as np
# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), 7)
print("\n3. Array filled with 7 (3x3):\n", fill_value_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\n4. Zeros Array with Same Shape as Reference Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\n5. Ones Array with Same Shape as Reference Array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy Array:\n", numpy_array)


1. Empty Array (2x2):
 [[1. 2.]
 [3. 4.]]

2. All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Array with Same Shape as Reference Array:
 [[0 0]
 [0 0]]

5. Ones Array with Same Shape as Reference Array:
 [[1 1]
 [1 1]]

6. Converted NumPy Array:
 [1 2 3 4]


In [ ]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing

# 1. Create an array with values ranging from 10 to 49.
array_10_49 = np.arange(10, 50)
print("\n1. Array with values ranging from 10 to 49:\n", array_10_49)

# 2. Create a 3X3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3X3 matrix with values ranging from 0 to 8:\n", matrix_3x3)

# 3. Create a 3X3 identity matrix.
identity_matrix = np.eye(3)
print("\n3. 3X3 identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4 .Random array of size 30:\n", random_array)
print("\n4.1. Mean of above array:\n", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values.
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\n5. 10X10 array with random values:\n", random_matrix)
print("\n5.1. Minimum Value:\n", min_value)
print("\n5.2. Maximum Value:\n", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing starts from 0
print("\n6. Zero array of size 10 and 5th element replaced with 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed Array:\n", reversed_arr)

# 8. Create a 2d array with 1 on border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2d array with 1 on border and 0 inside:\n", border_array)

# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8X8 matrix filled with a checkerboard pattern:\n", checkerboard)


1. Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3X3 matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3X3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4 .Random array of size 30:
 [0.27267489 0.95503187 0.04841929 0.72212096 0.45633473 0.95087403
 0.16422678 0.07414694 0.808924   0.15814064 0.52258234 0.22271301
 0.1261825  0.25839037 0.3381184  0.23659775 0.68879838 0.62864667
 0.68756714 0.43761888 0.98221778 0.50976296 0.87723381 0.98701613
 0.21961089 0.06404462 0.21388398 0.78041725 0.13828012 0.64402134]

4.1. Mean of above array:
 0.47248661513648565

5. 10X10 array with random values:
 [[0.45332907 0.67785653 0.1118815  0.47988222 0.2274271  0.47840773
  0.57717009 0.33749311 0.38720387 0.68326434]
 [0.42026298 0.38542759 0.86645283 0.24395195 0.57735177 0.1480326
  0.60111966 0.9107746  0.16042464 0.26171088]
 [0.8928047

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

# 3. Multiply the array x with any integer (e.g., 3)
mult_x = x * 3
print("\nMultiplication of x with 3:\n", mult_x)

# 4. Find the square of each element of x
square_x = x ** 2
print("\nSquare of each element of x:\n", square_x)

# 5. Dot product calculations
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\nDot product of v and w:", dot_vw)
print("\nDot product of x and v:\n", dot_xv)
print("\nDot product of x and y:\n", dot_xy)

# 6. Concatenation
concat_xy_row = np.concatenate((x, y), axis=0)  # Along rows
concat_vw_col = np.vstack((v, w))  # Along columns

print("\nConcatenation of x and y along rows:\n", concat_xy_row)
print("\nConcatenation of v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempting to concatenate x and v
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)
    print("Reason: x has shape (2,2) and v has shape (2,). Their dimensions are incompatible for direct concatenation.")


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element of x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x has shape (2,2) and v has shape (2,). Their dimensions are incompatible for direct concatenation.


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)

identity_matrix = np.dot(A, A_inv)

print("A * A_inv:\n", identity_matrix)
print("\nIdentity Matrix:\n", np.eye(2))  # Expected identity matrix


A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity Matrix:
 [[1. 0.]
 [0. 1.]]


In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAre AB and BA equal?", np.array_equal(AB, BA))


AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Are AB and BA equal? False


In [ ]:
AB_T = np.transpose(AB)

BT = np.transpose(B)
AT = np.transpose(A)
BT_AT = np.dot(BT, AT)

print("\n(AB)^T:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)
print("\nAre (AB)^T and B^T * A^T equal?", np.array_equal(AB_T, BT_AT))



(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

Are (AB)^T and B^T * A^T equal? True


In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("\nSolution for (x, y, z):\n", X)


In [ ]:
import numpy as np
import time

# 1. Element-wise Addition
size = 1_000_000

# Generate lists and arrays
list1 = list(range(size))
list2 = list(range(size))

array1 = np.arange(size)
array2 = np.arange(size)

# Using Python lists
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise addition using lists:", end_time - start_time, "seconds")

# Using NumPy arrays
start_time = time.time()
array_addition = array1 + array2
end_time = time.time()
print("Time taken for element-wise addition using NumPy:", end_time - start_time, "seconds")


# 2. Element-wise Multiplication

# Using Python lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("\nTime taken for element-wise multiplication using lists:", end_time - start_time, "seconds")

# Using NumPy arrays
start_time = time.time()
array_multiplication = array1 * array2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy:", end_time - start_time, "seconds")


# 3. Dot Product

# Using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print("\nTime taken for dot product using lists:", end_time - start_time, "seconds")

# Using NumPy arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()
print("Time taken for dot product using NumPy:", end_time - start_time, "seconds")


# 4. Matrix Multiplication
matrix_size = 1000

# Generate matrices
matrix1_list = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2_list = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]

matrix1_np = np.array(matrix1_list)
matrix2_np = np.array(matrix2_list)

# Using Python lists
start_time = time.time()
result_matrix_list = [[sum(matrix1_list[i][k] * matrix2_list[k][j] for k in range(matrix_size))
                       for j in range(matrix_size)] for i in range(matrix_size)]
end_time = time.time()
print("\nTime taken for matrix multiplication using lists:", end_time - start_time, "seconds")

# Using NumPy arrays
start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print("Time taken for matrix multiplication using NumPy:", end_time - start_time, "seconds")


Time taken for element-wise addition using lists: 0.14121150970458984 seconds
Time taken for element-wise addition using NumPy: 0.013669013977050781 seconds

Time taken for element-wise multiplication using lists: 0.13476109504699707 seconds
Time taken for element-wise multiplication using NumPy: 0.012082338333129883 seconds

Time taken for dot product using lists: 0.09989690780639648 seconds
Time taken for dot product using NumPy: 0.0018846988677978516 seconds

Time taken for matrix multiplication using lists: 205.71187567710876 seconds
Time taken for matrix multiplication using NumPy: 2.343365430831909 seconds
